spring:
  application:
    name: hello-spring-cloud-config
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      label: master
      server:
        git:
          uri: ${git.uri}
          search-paths: ${git.search-paths}
          username: ${git.username}
          password: ${git.password}
  profiles:
    include: git

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

